services:
  api-travel-orders:
    container_name: api-travel-orders
    image: edilsonss123/php:8.2
    ports:
      - '2050:8000'
    restart: always
    volumes:
      - ./api-travel-orders:/var/www/apps/api-travel-orders
      - ./data/conf.d/memory.ini:/usr/local/etc/php/conf.d/docker-php-ext-memory.ini
      - ./data/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./data/api/entrypoint.sh:/var/www/apps/api-travel-orders/entrypoint.sh
    depends_on:
      - db-travel-orders
    networks: 
      - net-travel
    command: /bin/bash /var/www/apps/api-travel-orders/entrypoint.sh
  db-travel-orders:
    image: mysql:8.0
    container_name: db-travel-orders
    environment:
      MYSQL_ROOT_PASSWORD: "8plin#9@trtert"
      MYSQL_DATABASE: travel-orders
      MYSQL_USER: travel-user
      MYSQL_PASSWORD: "8teste0rd&"
      restart: always
    ports:
      - "3358:3306"
    volumes:
      - ./data/mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - db_data:/var/lib/mysql
    networks:
      - net-travel
  nginx-resultado-test:
      image: nginx:latest
      container_name: nginx-resultado-test
      ports:
        - "2052:80"
      volumes:
        - ./api-travel-orders/report/tests:/usr/share/nginx/html
        - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      restart: always
volumes:
  db_data:

networks: 
  net-travel:
    name: net-travel