services:
  api-travel-orders:
    container_name: api-travel-orders
    image: edilsonss123/php:8.2
    ports:
      - '2050:8000'
    volumes:
      - ./api-travel-orders:/var/www/apps/api-travel-orders
      - ./data/api/entrypoint.sh:/var/www/apps/api-travel-orders/entrypoint.sh
    depends_on:
        - db-travel-orders
    networks: 
      - net-travel
    command: /bin/bash /var/www/apps/api-travel-orders/entrypoint.sh
  db-travel-orders:
    image: mysql:8.0
    container_name: db-travel-orders
    environment:
      MYSQL_ROOT_PASSWORD: "8plin#9@trtert"
      MYSQL_DATABASE: travel-orders
      MYSQL_USER: travel-user
      MYSQL_PASSWORD: "8teste0rd&"
    ports:
      - "3358:3306"
    volumes:
      - ./data/mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - db_data:/var/lib/mysql
    networks:
      - net-travel

volumes:
  db_data:

networks: 
  net-travel:
    name: net-travel