services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    depends_on:
      - sonarqube-db
    networks:
      - sonar-net
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - 9000:9000
    restart: always
    volumes:
      - ./data/sonar-data:/opt/sonarqube/data
      - ./data/sonarqube-logs:/opt/sonarqube/logs

  sonarqube-db:
    image: postgres:13
    container_name: sonarqube-db
    shm_size: 128mb
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    networks:
      - sonar-net
    restart: always
    volumes:
      - ./data/sonar-db:/var/lib/postgresql
  

networks:
  sonar-net:
    driver: bridge