name: publish-github-page

on:
  workflow_call:

jobs:
  publish-github-page:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: coverage-and-infection-tests
          path: docs

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Convert Markdown to GitHub Pages
        uses: wranders/markdown-to-pages-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            README.md
          out_path: docs
          custom_css: https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.2.0/github-markdown-light.min.css  # Aplica o CSS desejado

      - name: List docs directory (after conversion)
        run: ls -R

      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs  # O diretório 'docs' agora deve conter o index.html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Output Deployment URL
        run: echo "Deployed to ${{ steps.deployment.outputs.page_url }}"
