name: test-app

on:
  workflow_call:

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'

      - uses: actions/checkout@v4

      - name: Recuperando arterfato da aplicação gerado no fluxo principal 
        uses: actions/download-artifact@v4.1.3
        with:
          name: api-travel-orders
          path: api-travel-orders
          
      - name: Execute tests Unit via PHPUnit
        working-directory: ./api-travel-orders
        run: php artisan test --filter Unit

      - name: Create Database
        run: |
          mkdir -p ./api-travel-orders/database
          touch ./api-travel-orders/database/database.sqlite
          chmod 777 ./api-travel-orders/database/database.sqlite

      - name: Migrate Database
        run: php artisan migrate
        working-directory: ./api-travel-orders

      - name: Execute tests Feature via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ${{ github.workspace }}/api-travel-orders/database/database.sqlite
        working-directory: ./api-travel-orders
        run: php artisan test --filter Feature
