name: test-app

on:
  workflow_call:

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'

      - uses: actions/checkout@v4

      - name: Recuperando arterfato da aplicação gerado no fluxo principal 
        uses: actions/download-artifact@v4.1.1
        with:
          name: api-travel-orders
          path: api-travel-orders

      - name: list folder
        run: find . -type d -mindepth 1 -maxdepth 3

      # - name: Copy .env
      #   working-directory: ./api-travel-orders
      #   run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # - name: Install Dependencies
      #   working-directory: ./api-travel-orders
      #   run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # - name: Generate key
      #   working-directory: ./api-travel-orders
      #   run: php artisan key:generate

      # - name: Directory Permissions
      #   working-directory: ./api-travel-orders
      #   run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
          
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        working-directory: ./api-travel-orders
        run: php artisan test
