name: test-app

on:
  workflow_call:

jobs:
  common-setup:
    runs-on: ubuntu-latest
    outputs:
      database-path: ${{ github.workspace }}/api-travel-orders/database/database.sqlite
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'

      - uses: actions/checkout@v4

      - name: Recuperando artefato da aplicação gerado no fluxo principal
        uses: actions/download-artifact@v4.1.3
        with:
          name: api-travel-orders
          path: api-travel-orders

      - name: Create Database
        run: |
          mkdir -p ${{ github.workspace }}/api-travel-orders/database
          touch ${{ github.workspace }}/api-travel-orders/database/database.sqlite
          chmod 777 ${{ github.workspace }}/api-travel-orders/database/database.sqlite

      - name: Migrate Database
        run: php artisan migrate --env=testing
        working-directory: ${{ github.workspace }}/api-travel-orders

      - name: JWT APP
        run: php artisan jwt:secret --env=testing
        working-directory: ${{ github.workspace }}/api-travel-orders

  unit-tests:
    runs-on: ubuntu-latest
    needs: common-setup
    steps:
      - name: Execute tests Unit via PHPUnit
        working-directory: ${{ github.workspace }}/api-travel-orders
        run: php artisan test --filter Unit --env=testing

  feature-tests:
    runs-on: ubuntu-latest
    needs: common-setup
    steps:
      - name: Execute tests Feature via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ${{ needs.common-setup.outputs.database-path }}
        working-directory: ${{ github.workspace }}/api-travel-orders
        run: php artisan test --env=testing --filter Feature

  coverage:
    runs-on: ubuntu-latest
    needs: [unit-tests, feature-tests]
    steps:
      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'

      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPUnit with Coverage
        run: |
          php artisan test:coverage --env=testing
        working-directory: ${{ github.workspace }}/api-travel-orders

      - name: Upload Coverage Results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./tests/result/coverage

  infection:
    runs-on: ubuntu-latest
    needs: [unit-tests, feature-tests]
    steps:
      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'

      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest

      - name: Install Infection
        run: |
          composer require infection/infection --dev

      - name: Run Infection
        run: |
          php artisan test:mutation --env=testing
        working-directory: ${{ github.workspace }}/api-travel-orders

      - name: Upload Infection Report
        uses: actions/upload-artifact@v4
        with:
          name: mutation-report
          path: ./tests/result/mutation
